# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: src/i18n_check/test_frontends/all_checks_fail
i18n-dir: src/i18n_check/test_frontends/all_checks_fail/test_i18n
i18n-src: src/i18n_check/test_frontends/all_checks_fail/test_i18n/test_i18n_src.json

file-types-to-check: [.ts]

checks:
  # Global configurations applied to all checks.
  global:
    active: true               # Enable all checks by default
    directories-to-skip: []    # Add any directories you want to exclude here
    files-to-skip: []          # Add specific files to exclude here

  invalid-keys:
    active: true
    directories-to-skip: []
    files-to-skip: []
    keys-to-ignore: ""         # Regex pattern for keys to ignore

  non-existent-keys:
    active: true
    directories-to-skip: []
    files-to-skip: []

  unused-keys:
    active: true
    directories-to-skip: []
    files-to-skip: []

  non-source-keys:
    active: true

  repeat-keys:
    active: true

  repeat-values:
    active: true

  nested-keys:
    active: true
